vivienda_home:
    path:     /
    defaults: { _controller: AlienigenaViviendaBundle:Site:index }
vivienda_login:
    path:     /login
    defaults: { _controller: AlienigenaViviendaBundle:Site:login }