vivienda_home:
    path:     /
    defaults: { _controller: AlienigenaViviendaBundle:Site:index }
panel_home:
    path:     /panel
    defaults: { _controller: AlienigenaViviendaBundle:Panel:index }
logout:
    path: /logout